### ISSUE TITLE
documentation missing

### ISSUE THREAD

**Issue by blueamerican** [visuellverstehen/t3googleanalytics#5]
it would be helpful, if there is a screen or hint, where to find the google id in the BE!
This is not "visuellverstehen"

**Comment by malteriechmann** [comment]
Hi @blueamerican,
sure, we should add some documentation including screenshots.

What do you mean by »This is not "visuellverstehen"«?

Best regards
Malte

**Comment by malteriechmann** [comment]
My colleague explained to me what you meant by »This is not "visuellverstehen"«. I did not get the pun. Thanks again for your feedback.

We will add a proper documentation with screenshots.

**Comment by blueamerican** [comment]
what i mean is: i guess not all people find the id field in the backend without a help..
visuellverstehen would be a kind of oppositie of this..

**Comment by shabnamKhan** [comment]
**Steps to add Google ID in backend:**
Go to Admin Panel -> Templates -> Choose Info/ Modify -> Click on Edit whole Template record( which is common for all pages) -> Google Analytics Tab -> Add GA ID in "Google Analytics Tracking-ID" Input box


![TYPO3 CMS 9 5 8 ](https://user-images.githubusercontent.com/2337693/64471407-12e3ba00-d16f-11e9-840c-2b7b4b2df39c.png)


After add tracking code. Sample code for enable and disable Google Analytics.
```
<a onclick="return googleAnalyticsEnable();">Enable GA Opt Tracking</a> <br />
<a onclick="return googleAnalyticsDisable();">Disbale GA Opt Tracking</a>
```
